name: Application
include: ../project.yml
targets:
  Canoe:
    templates: [BaseApp, BaseDependencies]
    testTargets:
      - CanoeTests

  CanoeTests:
    templates: [BaseAppTests, BaseTestDependencies]
    dependencies:
      - target: Canoe
