include:
  - path: Configurations/options.yml
    relativePaths: false
  - path: Configurations/targets.yml
    relativePaths: false
  - path: Configurations/schemes.yml
    relativePaths: false
  - path: Configurations/configs.yml
    relativePaths: false

name: Canoe