name: Application
include: ../project.yml
targets:
  Canoe:
    templates: [BaseApp, BaseDependencies]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.CanoeX.Canoe
        PRODUCT_NAME: Canoe
    testTargets:
      - ApplicationTests

  ApplicationTests:
    templates: [BaseAppTests, BaseTestDependencies]
    dependencies:
      - target: Canoe
