#!/usr/bin/env bash
#
# CopyPaste detection

set -euo pipefail
IFS=$'\n\t'

cd "${0%/*}/.."

pmd cpd \
	--files Projects/App/Sources \
	--files Projects/Profile/Sources \
	--minimum-tokens 50 --language swift --encoding UTF-8 \
	--format net.sourceforge.pmd.cpd.XMLRenderer --failOnViolation true >cpd-output.xml

# Running script
php Scripts/cpd_script.php -cpd-xml cpd-output.xml
